### ISSUE TITLE
Presença na Udesc

### ISSUE THREAD

**Issue by matstavares** [fsblemos/minicurso-vue#1]
Olá querida Fernanda, ainda estou esperando vc aqui. A gente só quer saber como é a vida fora daqui, se existe uma...os professores ja formados compõe as pessoas no "palco". Tem 4 professores e 3 egressos, tem exatamente 1 cadeira sobrando

**Comment by fsblemos** [comment]
Oi Mateus! Desculpe a demora para responder. Lembrei essa semana que tinha
marcado um compromisso com uns amigos e infelizmente não deu pra ir na
UDESC.

Obrigada de verdade pelo convite e desculpe não poder ter ido.

Abraços.

Em Sex, 22 de set de 2017 18:53, Mateus Seenem Tavares <
notifications@github.com> escreveu:
